### ISSUE TITLE
📂 Project base tools and organization

### ISSUE THREAD

**Issue by 6im0n** [epitech-mirroring/Zappy#24]
# 👮‍♂️ What's needed
Project base tools and organization management

## 📋 Subtasks
- [x] Root makefile 
- [x] Makefile for IA
- [x] Makefile for server
- [x] Makefile for GUI
- [x] Husky
- [x] Jenkins 
- [x] Gitignore
- [x] Editor config
- [x] README
- [x] Issue template
- [x] Main protection
- [x] Set PR review setting

### :bento:  assets for the readme

![fond-pierres-precieuses-colorees_1000526-113(1)](https://github.com/epitech-mirroring/Zappy/assets/46846093/14fa682c-172d-4a85-abfb-49fd6cb5c19d)

![image](https://github.com/epitech-mirroring/Zappy/assets/46846093/064d09b2-799c-4f13-8acd-c88e198a483c)
